Adding checks to make sure required applications exist

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -13,6 +13,28 @@ function log_error() {
 set -e
 set +x
 
+
+if ! command -v aws &> /dev/null
+then
+    echo "aws cli tools could not be found"
+    echo "go here to install https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
+    exit 1
+fi
+
+if ! command -v docker &> /dev/null
+then
+    echo "docker could not be found"
+    echo "go here to install https://docs.docker.com/engine/install/ubuntu"
+    exit 1
+fi
+
+if ! command -v jq &> /dev/null
+then
+    echo "jq could not be found"
+    echo "make sure to run: sudo apt install jq"
+    exit 1
+fi
+
 export AWS_DEFAULT_REGION=us-west-2
 ENVIRONMENT_NAME="staging"
 IMAGE_NAME=""
